### ISSUE TITLE
Disable physics jitter fix automatically when this plugin is enabled

### ISSUE THREAD

**Issue by Calinou** [lawnjelly/smoothing-addon#12]
To prevent mistakes ([like I've done for so long…](https://github.com/Calinou/escape-space/commit/0af6889c9db73bdd67896374bf98f9c95c49fe2d)), we could probably disable the physics jitter fix automatically whenever this plugin is enabled. This means we'd be making the assumption that the smoothing add-on is used on all physics bodies, but it's likely the case in real-world projects anyway.

**Comment by lawnjelly** [comment]
Yup I've been meaning to try and do this, I don't think I realised whether it was possible earlier. :+1:

**Comment by Calinou** [comment]
Fixed by https://github.com/lawnjelly/smoothing-addon/commit/f76809e7c81d6f84298a71299acfef2a9a1d7dfd and https://github.com/lawnjelly/smoothing-addon/commit/7b14ac968e3b33b77e98ef00f0d1905d2070faab.
