### ISSUE TITLE
[Godot 4.x] Smoothing node that has a sprite with a target of CharacterBody2D always enters the scene at the origin

### ISSUE THREAD

**Issue by sugarsthenewwhite** [lawnjelly/smoothing-addon#26]
I have a player with a node structure like this;
![image](https://user-images.githubusercontent.com/53354625/223199324-93f5af12-8222-4933-817e-3707b8c411b8.png)
and whenever i run the scene (or another scene that its placed to) no matter where i place the player in the editor the visual representative always starts at the origin, the collision shape as you can see remains at where i moved the player back in the editor, however the sprite always begins the scene at the origin, smoothing seems to work but it looks very weird and is unusable as sprite and the body are at different places.
![image](https://user-images.githubusercontent.com/53354625/223199146-4909d64d-2500-4c3e-a1d3-b4779fa983f1.png)
Here is the sample project, you can run the "Testing" scene and see the issue yourself. (Sorry if i made a mistake and this isn't actually an issue but when i try the same thing at Godot 3.x it works fine)
[SmoothingCharacterBody2DIssue.zip](https://github.com/lawnjelly/smoothing-addon/files/10901759/SmoothingCharacterBody2DIssue.zip)

**Comment by lawnjelly** [comment]
Just set the `GLOBAL_IN` flag to true, and it works. It is probably something I mucked up with a recent update whereby all nodes are set as top level, and so are expecting a global input.

I'll see about fixing this properly tomorrow. :+1:

**Comment by lawnjelly** [comment]
Ok I've updated the addon for both 3.x and 4.x, and defaulted both to use global mode for 2D, which should be more foolproof. I had forgotten that the 2D previously defaulted to local mode.
