### ISSUE TITLE
Can't import to Godot 4.x

### ISSUE THREAD

**Issue by Skuttle-Studios** [lawnjelly/smoothing-addon#34]
I'm trying to make an infinite runner in Godot 4, however when I try to import, it says it can't. Furthermore, I look into the files, and many of them have Godot 3 syntax. This confuses me because others _can_ run it on Godot 4. Can someone plz explain to me what I can do to fix? Probably a stupid question, I'm fairly new to Godot.

**Comment by lawnjelly** [comment]
Double check you are using the 4.x version of the addon:
https://github.com/lawnjelly/smoothing-addon/tree/4.x

This could be confusing if you haven't used github before. At the top left there is a selection box that shows you different branches of code, and for the smoothing addon there is a 3.x and 4.x branch.

If you look at the text file `readme.md` in the version you have it will say whether it is for 3.x or 4.x. :+1:

**Comment by Skuttle-Studios** [comment]
Aha! Thanks so much!
