### ISSUE TITLE
Flip being smoothed 

### ISSUE THREAD

**Issue by ky000** [lawnjelly/smoothing-addon#37]
I have a problem: the addon is smoothing the character's "flip," which is the negative scale. I wish there was a way not to smooth this. Unfortunately, if I disable the option scale from inspector.. everything gets messed up. I saw that I can use Teleport to change the position without interpolation... But would it work for my case?

**Comment by lawnjelly** [comment]
Ah yes, I am amazed no one has reported this before. I fixed this exact problem in the 2D core interpolation for 3.6 recently, but there is no accounting for it in the addon, I will take a look.

I'm guessing this was for 2D? The problem I saw was mostly occurring for sprites changing from facing e.g. left to right.

**Comment by lawnjelly** [comment]
These are the lines that deal with it in core:
https://github.com/godotengine/godot/blob/5271c971f346fcf3859f5872049f948afa4dba99/core/math/transform_interpolator.cpp#L40C1-L47

**Comment by lawnjelly** [comment]
This is fixed in 3.x branch, I'll shortly be updating 4.x. I did a significant rework for the 2D to solve some other problems and added the fix for the flip.

**Comment by ky000** [comment]
> This is fixed in 3.x branch, I'll shortly be updating 4.x. I did a significant rework for the 2D to solve some other problems and added the fix for the flip.

This will save my life. It happened exactly as you mentioned in 2d.. Facing right and left(flip). I'm using godot 4.x. I'll wait until you update
