### ISSUE TITLE
Heavy jitter from Camera2D scroll on Godot 4.2 (beta1)

### ISSUE THREAD

**Issue by aitorciki** [lawnjelly/smoothing-addon#46]
Hi there!

I'm trying to use the smoothing add-on in a top-down 2D setup, but this far I'm failing to make it work with a `Camera2D` that scrolls to follow the character.

I think I've setup the scene as documented (find [MRP](https://github.com/lawnjelly/smoothing-addon/files/12918875/PhysicsInterpolation.zip) attached), no pixel snapping is enabled:

```
CharacterBody2D
|__Smoothing2D
   |__Sprite2D
      |__Camera2D
```

When both FPS and physics ticks are set at 60, everything looks good:

https://github.com/lawnjelly/smoothing-addon/assets/428243/9ef715b5-ea21-45f0-bc3b-cb069bef73a7

When reducing physics ticks to 20/s, stutter is very bad on camera scroll, it looks like `Camera2D` and `Smoothing2D` are fighting:

https://github.com/lawnjelly/smoothing-addon/assets/428243/bda2bf84-59f4-463f-bdd2-a1840b371cd9

When setting the camera to run on `physics`, instead of `idle`, jitter is not that bad, but still very bad:

https://github.com/lawnjelly/smoothing-addon/assets/428243/44b36c9f-a22f-4c89-bf0e-d74e4d819801

Smoothing the camera position fixes it! But forces to use a smoothed camera, which I didn't intend to (the recording doesn't actually show the camera's delay behind the character, happens in real-time play though):

https://github.com/lawnjelly/smoothing-addon/assets/428243/503aad46-dc97-4962-b852-ab0f940460ca

As usual, setting `Smoothing2D` as `toplevel` fixes the jitter, but breaks y-sorting, which is a deal-breaker:

https://github.com/lawnjelly/smoothing-addon/assets/428243/fe4134fa-c0c2-44ae-8abd-ccaebbc724ba

I've also tried to make `Camera2D` a child of all the other nodes, with the same result.

Is my setup wrong / am I missing something? Or is Godot 4.2's `Camera2D` known to break the add-on?

Thanks for your time and for a great tool!

(By the way, amazing pixel art by https://limezu.itch.io/!)

**Comment by lawnjelly** [comment]
Ah I have a feeling I need to revert some of the instructions to prior to adding the `toplevel` feature, which is now defaulted to off (which was the old system). This means that in many cases it will be better to have the visual representation and camera not as a child of the object being moved, and set them up to follow the target.

I'll give more info once I've reminded myself of the problem with your MRP.

**Comment by aitorciki** [comment]
Splitting physics and visuals into separate branches + explicit tracking in the smoothing node worked like a charm!

There is still some wonky initial render where the character is moved to its initial position in the scene, I'll play with teleporting and see if I can make it work.

Just being curious: when should the smoothing node be a child of the physics body vs using separate branches? Maybe docs clarifying when to use which would help newcomers like myself?

**Comment by lawnjelly** [comment]
I absolutely need to update the docs (really to what they used to be last year).

Separating the visual rep from the physics rep is recommended when not using `toplevel`. When using `toplevel` you don't need to do this (but you lose y sorting).

The core physics interpolation totally fixes this problem because it introduces a new mode for 2D items where they don't inherit the parent transform. But we have to bodge this for the addon until this is available in 4.x, hence these workarounds.

2D physics interpolation is available in core in 3.x now from the next 3.6 beta.

**Comment by lawnjelly** [comment]
Ok I've tried to add back some of the relevant info to the `readme.md`.

It could probably do with another pass to make easier to read but I'm short of time right now so hopefully it should help. :+1:

**Comment by aitorciki** [comment]
I think the update to the readme will be very useful 👍 

Also, using `teleport` on the scene's `_ready` method has fixed the visible translation on initial render.

Everything works as expected now, closing the issue, thanks for your support!
