### ISSUE TITLE
How to use toplevel in 2D

### ISSUE THREAD

**Issue by zmnpl** [lawnjelly/smoothing-addon#47]
Hey, so I've read the paragraf on toplevel multiple times but have not clue how to make it work. The basic setup of the plugin including use was pretty simple but toplevel -  no idea.

So what works ![is this without toplevel](https://github.com/lawnjelly/smoothing-addon/assets/9001667/096d3e1a-d665-4520-be8c-f1dc1b617f35)
(Additional node: No target explicitly assigned on the smoothing node)

How would I set this up for toplevel, to test ist out?

Sorry if that might be obvious, but I'm new to godot (not to development) and cannot seem to figure it out.

Cheers!

Edit: Kudos for the plugin btw.! This is essential.

**Comment by zmnpl** [comment]
Okay, think I found out. I "just" needed to create another node as root of the scene which I didn't know how to before. So it really came down to my godot knowledge I think.
![like this](https://github.com/lawnjelly/smoothing-addon/assets/9001667/f837499f-d4ff-4564-a8ad-8abb1ca757a4)


Now I do have anothe issue with jitter (I think) but will create another issue for that.

**Comment by lawnjelly** [comment]
Yes using a separate branch for the smoothing node is recommended _unless_ you are using `toplevel`. And `toplevel` has some caveats as outlined in the readme: lack of y-sorting being the main one.
