### ISSUE TITLE
Lerping angle in 2D

### ISSUE THREAD

**Issue by oeleo1** [lawnjelly/smoothing-addon#5]
I see that the 2D node is using a home made _LerpAngle() function. What is the reason for not using the lerp_angle() builtin? Apart from that -- great work!

**Comment by lawnjelly** [comment]
I think it was written before lerp_angle was added to core (July 2019 #30693). I was going to suggest changing it, but in fact that's a good reason to keep as it is, so it will work on previous Godot versions. :+1:

**Comment by Calinou** [comment]
@lawnjelly This add-on already uses `Engine.get_physics_interpolation_fraction()`, which was added to Godot 3.2. Therefore, this add-on can't work with Godot 3.1.

**Comment by lawnjelly** [comment]
Ah good point lol! :grin:
So it's more of a historical accident.

If anyone wants to change it, feel free to make a PR! :+1:
