### ISSUE TITLE
problem with spawning scene with smoothing

### ISSUE THREAD

**Issue by xRaska** [lawnjelly/smoothing-addon#50]
i noticed that when spawning scenes that has this addon, at _ready it will always interpolate from the origin to the point you want the scene to spawn. i looked in the code and i replaced at line 36 this:

`var _m_Trans_curr: Transform2D = Transform2D()

var _m_Trans_prev: Transform2D = Transform2D()`

with this:

`@onready var _m_Trans_curr: Transform2D = get_parent().transform

@onready var _m_Trans_prev: Transform2D = get_parent().transform`

and so far it worked like a charm. for sure it's probably not the best way to go about it (probably), but i wonder if you could implement the fix in a way or another.
:)

**Comment by lawnjelly** [comment]
Quoting from the docs:

> Teleporting
> There is one special case when using smoothing nodes - the case when you want a target to instantaneously move from one location to another (for instance respawning a player, or at level start) where you do not want interpolation from the previous position. In this special case, you should move the target node (by setting the translation or position), and then call the 'teleport' function in the Smoothing node. This ensures that interpolation will be switched off temporarily for the move. Make sure to call teleport AFTER moving the target node, rather than before.

Depending on your use case in your game, you can call teleport in `_ready()` or do what you have done (which is functionally the same). 2D core interpolation actually does this now on entering the scene tree, but core interpolation 3D does not (I think from memory there were some situations where it wasn't wanted, but I wrote this a while ago now).

**Comment by xRaska** [comment]
ah, my bad then, i swear it completely went past my eyes when reading the readme. so sorry

**Comment by lawnjelly** [comment]
No problem, it's something I may revisit eventually. :+1:

**Comment by rmallermartins** [comment]
> Depending on your use case in your game, you can call teleport in `_ready()` or do what you have done (which is functionally the same). 2D core interpolation actually does this now on entering the scene tree, but core interpolation 3D does not (I think from memory there were some situations where it wasn't wanted, but I wrote this a while ago now).

I just downloaded 4.x and teleport not happening "on entering the scene tree"

**Comment by lawnjelly** [comment]
> I just downloaded 4.x and teleport not happening "on entering the scene tree"

That is something to report on [godot github](https://github.com/godotengine/godot/issues), I was referring to 3.x (at the time of my post there was no core interpolation in 4.x). rburing is maintaining 4.x (although admittedly based on forward port of my 3.x version).

**Comment by rmallermartins** [comment]
Sorry, didn't know about that, but is rburing maintaining the 4.x branch on this Repo, or should I use something else? Got a little bit confused now 😅

**Comment by lawnjelly** [comment]
> Sorry, didn't know about that, but is rburing maintaining the 4.x branch on this Repo, or should I use something else? Got a little bit confused now 😅

It is confusing I'll admit.

### Godot 3.x
Has built in 3D physics interpolation from 3.5.
Has built in 2D physics interpolation from 3.6.

### Godot 4.x
Has built in 2D physics interpolation from 4.3 (afaik). Although it is not feature complete, particles are not yet implemented.

That means there is no longer a need to use the smoothing addon in 3.x (provided you use up to date engine), and soon there will be no need to use it for 2D in 4.x.
