### ISSUE TITLE
"Ghosting" effect when hide and show object

### ISSUE THREAD

**Issue by vrpferreira** [lawnjelly/smoothing-addon#55]
Hi!
This addon is incredible, the movement of the character and other objects has become much smoother. However, I have a problem, where I hide an object, but when I make it visible again, for a moment, the object appears in the last position where it was seen before being hidden and then immediately moves to the correct position.

On 22 seconds, you can see that. The video is in slow motion.

https://github.com/lawnjelly/smoothing-addon/assets/55215012/815eae8e-fab7-44c6-a1f2-6293a8bf6b11

**Comment by lawnjelly** [comment]
You probably need a `teleport()` on unhiding. See:
https://github.com/lawnjelly/smoothing-addon?tab=readme-ov-file#teleporting

**Comment by vrpferreira** [comment]
Man, really, you are a *** god! Thank you!
