### ISSUE TITLE
Physical Bones 

### ISSUE THREAD

**Issue by Haewen** [lawnjelly/smoothing-addon#57]
Hi, thanks for the addon!
I was wondering if physical bones are supported by this. 
It doesn't look like they are, but it's absolutely possible that I might just be doing stuff wrong.
I added a smoothing node to my Skeleton3D and parented the character mesh to it. 
I'm using Godot 4.2.

**Comment by lawnjelly** [comment]
Away from home at moment but you may need to parent the skelton to the smoothing node, rather than other way around.

**Comment by Haewen** [comment]
Oh, yeah that seems to have done the trick, thank you!
Didn't think of parenting the whole skeleton to the Smoothing node.
